apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "service-broker-proxy.fullname" . }}
  labels:
    app: {{ template "service-broker-proxy.name" . }}
    chart: {{ template "service-broker-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "service-broker-proxy.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "service-broker-proxy.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "service-broker-proxy.fullname" . }}-config
      serviceAccountName: {{ template "service-broker-proxy.fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: config-volume
          mountPath: {{ .Values.file.location }}
          readOnly: true
        env:
        - name: SELF_URL
          value: http://{{ template "service-broker-proxy.name" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}
        - name: SM_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "service-broker-proxy.fullname" . }}-secret
              key: sm_user
        - name: SM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "service-broker-proxy.fullname" . }}-secret
              key: sm_password
        - name: K8S_REG_SECRET_NAME
          value: {{ template "service-broker-proxy.fullname" . }}-regsecret
        - name: K8S_REG_SECRET_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: K8S_REG_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "service-broker-proxy.fullname" . }}-regsecret
              key: username
        - name: K8S_REG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "service-broker-proxy.fullname" . }}-regsecret
              key: password
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
        args:
        - "--file.location={{ .Values.file.location }}"
        - "--file.name={{ .Values.file.name }}"
        - "--file.format={{ .Values.file.format }}"
